{% set name = "functional_algorithms" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/functional_algorithms-{{ version }}.tar.gz
  sha256: da535841039b80ee4ca155d6cdae7a588a3868351a6c62542789ca1e542bfc3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.11
    - black
    - numpy
    - mpmath

test:
  requires:
    - pip
    - pytest
  commands:
    - python -c "import functional_algorithms as fa; print(fa.__version__)"
    - pytest -sv -r s --pyargs functional_algorithms
    - pip check
  imports:
    - functional_algorithms
    - functional_algorithms.targets
    - functional_algorithms.tests

about:
  home: https://github.com/pearu/functional_algorithms
  summary: Functional algorithms and implementations
  dev_url: https://github.com/pearu/functional_algorithms
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pearu
